spring:
  application:
    name: notification
  profiles:
    active: local

  r2dbc:
    url: r2dbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    name: ${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    properties:
      show-sql: true

  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schemas: ${DB_SCHEMAS}
    default-schema: ${DB_DEFAULT_SCHEMA}
    baseline-on-migrate: true
    callback-locations: classpath:db/migration
    driver-class-name: org.postgresql.Driver

  mail:
    port: ${MAIL_PORT}
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: ${MAIL_PROTOCOL}
    auth: ${MAIL_AUTH}
    enable: ${MAIL_ENABLE}
    require: ${MAIL_REQUIRE}
    ssl:
      enabled: false

server:
  port: 8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true