DB_URL: localhost
DB_PORT: 5432
DB_NAME: online_shop_users
DB_USERNAME: online_shop_user_owner
DB_PASSWORD: online_shop_user_owner
DB_SCHEMAS: users
DB_DEFAULT_SCHEMA: users

ARGON2_HASH_MEMORY: 50000
ARGON2_HASH_ITERATIONS: 3
ARGON2_HASH_PARALELISM: 3
ARGON2_HASH_HASH-LENGTH: 128
ARGON2_HASH_SALT-LENGTH: 128

JWT_ISSUER: http://localhost:8081
JWT_EXPIRATION: 3600000
JWT_ALGORITHM: RSA
JWT_PRIVATE-KEY-PATH: /Users/artyom_aroyan/Software/Java/.keys/private_key.pem
JWT_PUBLIC-KEY-PATH: /Users/artyom_aroyan/Software/Java/.keys/public_key.pem