spring:
  application:
    name: user
  profiles:
    active: local

  r2dbc:
    url: r2dbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    name: ${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    properties:
      show-sql: true

  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schemas: ${DB_SCHEMAS}
    default-schema: ${DB_DEFAULT_SCHEMA}
    baseline-on-migrate: true
    callback-locations: classpath:db/migration
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000ms
      repositories:
        enabled: false
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
    r2dbc:
      repositories:
        enabled: true

  security:
    argon2-hash:
      memory: ${ARGON2_HASH_MEMORY}
      iterations: ${ARGON2_HASH_ITERATIONS}
      parallelism: ${ARGON2_HASH_PARALELISM}
      hash-length: ${ARGON2_HASH_HASH-LENGTH}
      salt-length: ${ARGON2_HASH_SALT-LENGTH}

server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true

logging:
  level:
    org:
      springframework:
        r2dbc:
          info
    io:
      r2dbc:
        postgresql:
          QUERY: info
        security:
          access: info
          authentication: INFO
          authorization: INFO
        _: info
    am:
      online:
        shop:
          user:
            security: info