CREATE TABLE IF NOT EXISTS users (
    id UUID UNIQUE NOT NULL PRIMARY KEY ,
    username VARCHAR(15) UNIQUE NOT NULL ,
    password VARCHAR(1000) NOT NULL ,
    email VARCHAR(254) UNIQUE NOT NULL ,
    roles VARCHAR(100) NOT NULL ,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    active BOOLEAN DEFAULT FALSE,
    version BIGINT NOT NULL
)